publicHoistPattern:
  - '@vue/runtime-core'
  - exceljs

shellEmulator: true
trustPolicy: no-downgrade

packages:
  - playground/*
  - packages/*

onlyBuiltDependencies:
  - esbuild
  - unrs-resolver

registry: https://registry.npmmirror.com

allowBuilds:
  esbuild: true
