name: publish
on:
  push:
    branches:
      - master
jobs:
  release:
    if: ${{ github.actor == 'zhuchentong' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9.10.0
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build Package
        run: pnpm run build

      - name: Configure Git User
        run: |
          git config --global user.email "2037630@163.com"
          git config --global user.name "zhuchentong"

      - name: Create Release Pull Request or Publish
        id: changesets
        uses: changesets/action@v1
        with:
          publish: pnpm dlx changeset publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
  sync:
    runs-on: ubuntu-latest
    needs: release
    steps:
      - name: Sync Package
        run: |
          curl -X PUT "https://registry-direct.npmmirror.com/-/package/@gopowerteam/request/syncs" &&
          curl -X PUT "https://registry-direct.npmmirror.com/-/package/@gopowerteam/request-generate/syncs" &&